name: Helm OCI Chart Releaser
description: Push Helm charts to OCI-based (Docker) registries
author: routific
inputs:
  name:
    required: true
    description: Chart name
  repository:
    required: true
    description: Chart repository name
  tag:
    required: true
    description: Chart version
  path:
    required: false
    description: Chart path (Default 'charts/{name}')
  registry:
    required: true
    description: OCI registry
  registry_username:
    required: true
    description: OCI registry username
  registry_password:
    required: true
    description: OCI registry password
outputs:
  image:
    value: ${{ steps.output.outputs.image }}
    description: Chart image (Default '{registry}/{repository}/{image}:{tag}')
  artifact:
    value: ${{ steps.output.outputs.artifact }}
    description: Artifact path
runs:
  using: composite
  steps:
    - name: Helm | Login
      shell: bash
      run: echo -E ${{ inputs.registry_password }} | helm registry login -u ${{ inputs.registry_username }} --password-stdin ${{ inputs.registry }} --debug
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Package
      shell: bash
      run: helm package ${{ inputs.path == null && format('{0}/{1}', 'charts', inputs.name) || inputs.path }} --version ${{ inputs.tag }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Push
      shell: bash
      run: helm push ${{ inputs.name }}-${{ inputs.tag }}.tgz oci://${{ inputs.registry }}/${{ inputs.repository }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Logout
      shell: bash
      run: helm registry logout ${{ inputs.registry }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Output
      id: output
      shell: bash
      run: |
        echo "::set-output name=image::${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.name }}:${{ inputs.tag }}"
        echo "::set-output name=artifact::${{ inputs.name }}-${{ inputs.tag }}.tgz"
