name: PR Label Validator

on:
  workflow_call:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request label validator
        uses: Onemind-Services-LLC/actions-pr-label-enforcer@v1
