name: PR Title Validator

on:
  workflow_call:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: JIRA-prefix pull request title valiation
        uses: Onemind-Services-LLC/actions-pr-label-enforcer@v1
        with:
          github_token: ${{ github.token }} 
