name: PR Label Validator

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request label validator
        uses: mheap/github-action-required-labels@v5
        with:
          labels: "copy change, chore, bug, feature, refactor, hotfix"
          mode: minimum
          count: 1
