name: PR Label Validator

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request label validator
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          github-token: ${{ github.token }}
