name: PR Title Validator

on:
  workflow_call:
  
jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: JIRA-prefix pull request title valiation
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '\[((RT|DMT|BUG|V3R|UR|GTM)-\d+)\] +' # Regex the title should match.
          min_length: 5 # Min length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
